@startuml class-diagram

' IO package
interface io.UserIO
class io.UserIOImplConsole
class io.DataStoreFile
Class io.DataStoreException

' Controller package
interface controller.Controller
abstract class controller.ControllerImpl
class controller.ControllerCore
class controller.ControllerMainMenu
class controller.ControllerOrderMenu

' DAO package
interface dao.DAO
class dao.DAOImplFile
class dao.DAOException

' DTO package
class dto.Order
class dto.Product
class dto.StateTax
' enum dto.StateTaxEnum

' Service package
class service.InvalidDateStringException
class service.InvalidOrderException
interface service.ServiceLayer
class service.ServiceLayerImpl

' UI package
interface ui.View
abstract class ui.ViewImpl
class ui.ViewMenuMain
class ui.ViewOrder
class ui.ViewListOrders

' App
class App

' Relationships

io.UserIO <|-- io.UserIOImplConsole

io.DataStoreFile ..|> io.DataStoreException : <<throws>>

controller.Controller <|-- controller.ControllerImpl
controller.ControllerImpl <|-- controller.ControllerCore
controller.ControllerImpl <|-- controller.ControllerMainMenu
controller.ControllerImpl <|-- controller.ControllerOrderMenu
controller.ControllerCore "1" o-- "1" controller.Controller
controller.ControllerImpl "1" o-- "1" ui.View
controller.ControllerImpl "1" o-- "1" io.UserIO
controller.ControllerImpl "1" o-- "1" service.ServiceLayer

dao.DAO <|-- dao.DAOImplFile
dao.DAO ..|> dao.DAOException : <<throws>>
dao.DAOImplFile "1" *-- "3" io.DataStoreFile
dao.DAOImplFile "1" *-- "0..*" dto.Order
dao.DAOImplFile "1" *-- "0..*" dto.StateTax
dao.DAOImplFile "1" *-- "0..*" dto.Product

service.ServiceLayer ..|> dao.DAOException : <<throws>>
service.ServiceLayer ..|> service.InvalidDateStringException : <<throws>>
service.ServiceLayer ..|> service.InvalidOrderException : <<throws>>
service.ServiceLayer <|-- service.ServiceLayerImpl
service.ServiceLayer "1" o-- "1" dao.DAO

ui.ViewImpl --|> ui.View
ui.ViewImpl "1" o-- "1" io.UserIO
ui.ViewImpl <|-- ui.ViewMenuMain
ui.ViewImpl <|-- ui.ViewOrder
ui.ViewImpl <|-- ui.ViewListOrders
ui.ViewListOrders "1" *-- "1..*" dto.Order
ui.ViewOrder "1" *-- "1" dto.Order

App ..|> controller.Controller

@enduml
